on:
  push

name: rebuild

jobs:
  rebuild:
    name: "Rebuilding sundries"
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:devel
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Update DESCRIPTION
        run: |
          BiocManager::install("LTLA/rebook")
          rebook::updateDependencies(".")
        shell: Rscript {0}
      - name: Committing to master
        run: | 
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add DESCRIPTION
          git commit -m "Rebuilding DESCRIPTION." || true
          git push
